<?php $_htmlId      = $this->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $this->getElement()->getClass() ?>
<?php $_htmlName    = $this->getElement()->getName() ?>
<?php $_readonly    = $this->getElement()->getReadonly() ?>
<?php $_multiWebsite= $this->isMultiWebsites(); ?>
<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>
</tr>
<tr> 
    <td colspan="10" class="grid tier">
    <table cellspacing="0" class="data border" id="tiers_table">
        <?php if ($_multiWebsite): ?>
        <col width="135" />
        <?php endif; ?>
       <col width="120" />
        <col width="60" />
        <col width="140"/>
        <col width="60" />
        <thead>
         
            <tr class="headings">
                <th <?php if (!$_multiWebsite): ?>style="display:none"<?php endif; ?>><?php echo Mage::helper('sales')->__('Website') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Customer Group') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Qty') ?></th>
                <!-- Added -->
                <?php 
				if(Mage::getStoreConfig("mypackage/settings/wds_tier_price"))
				{
				?>
                <th><?php echo Mage::helper('catalog')->__('From Date') ?></th>
                <th><?php echo Mage::helper('catalog')->__('To Date') ?></th>
                <?php
				}
				?>
                <!-- -/- -->
                <th><?php echo $this->getPriceColumnHeader(Mage::helper('catalog')->__('Price')) ?></th>
                <th class="last"><?php echo Mage::helper('catalog')->__('Action') ?></th>
            </tr>
             
            <tr id="<?php echo $_htmlId ?>_add_template" class="template no-display">
                <!-- Website list -->
                <td <?php if (!$_multiWebsite): ?>style="display:none"<?php endif; ?>>
                <select disabled="no-template" class="<?php echo $_htmlClass ?> required-entry" name="<?php echo $_htmlName ?>[__index__][website_id]" id="tier_price_row___index___website">
                    <?php foreach ($this->getWebsites() as $_websiteId => $_info): ?>
                    <option value="<?php echo $_websiteId ?>"><?php echo $_info['name'] ?><?php if (!empty($_info['currency'])): ?> [<?php echo $_info['currency'] ?>]<?php endif; ?></option>
                    <?php endforeach ?>
                </select>
                </td>
                <!-- -/- -->
                 
                <!-- Customer Group -->
                <td>
                <select disabled="no-template" class="<?php echo $_htmlClass ?> custgroup required-entry" name="<?php echo $_htmlName ?>[__index__][cust_group]" id="tier_price_row___index___cust_group">
                    <?php foreach ($this->getCustomerGroups() as $_groupId=>$_groupName): ?>
                    <option value="<?php echo $_groupId ?>"><?php echo htmlspecialchars($_groupName) ?></option>
                    <?php endforeach ?>
                </select>
                </td>
                <!-- -/- -->
                 
                <!-- Qty -->
                <td class="nobr">
                    <input disabled="no-template" class="<?php echo $_htmlClass ?> qty required-entry validate-greater-than-zero" type="text" name="<?php echo $_htmlName ?>[__index__][price_qty]" value="'#{qty}'"  /> <small class="nobr"><?php echo Mage::helper('catalog')->__('and above')?></small>
                </td>
                <!-- -/- -->
                 
                <!-- Added -->
                <?php 
				if(Mage::getStoreConfig("mypackage/settings/wds_tier_price"))
				{
				?> 
                <td class="nobr">
                <input type="text" disabled="no-template" class="<?php echo $_htmlClass ?> required-entry" name="<?php echo $_htmlName ?>[__index__][from_date]" id="tier_price_row___index___from_date" style="width:68px">
                <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif'); ?>" id="tier_price_row___index___from_date_trig" />
                <script type="text/javascript">
				Calendar.setup({
					inputField : 'tier_price_row___index___from_date',
					//ifFormat : '%Y-%m-%e',
					ifFormat : '%m/%e/%Y',
					button : 'tier_price_row___index___from_date_trig',
					align : 'Bl',
					singleClick : true
				});
				</script>
               </td>
               <td class="nobr">
               <input type="text" disabled="no-template" class="<?php echo $_htmlClass ?> required-entry" name="<?php echo $_htmlName ?>[__index__][to_date]" id="tier_price_row___index___to_date" style="width:68px">
               <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif'); ?>" id="tier_price_row___index___to_date_trig" />
               <script type="text/javascript">
				Calendar.setup({
					inputField : 'tier_price_row___index___to_date',
					//ifFormat : '%Y-%m-%e',
					ifFormat : '%m/%e/%Y',
					button : 'tier_price_row___index___to_date_trig',
					align : 'Bl',
					singleClick : true
				});
				</script>
                </td>
                <!-- -/- -->
               <?php
			   }
			   ?>  
                <!-- Price -->
                <td>
                    <input disabled="no-template" class="<?php echo $_htmlClass ?> required-entry validate-greater-than-zero" type="text" name="<?php echo $_htmlName ?>[__index__][price]" value="'#{price}'" />
                </td>
                <!-- -/- -->
                 
                <!-- Button -->
                <td class="last"><input type="hidden" name="<?php echo $_htmlName ?>[__index__][delete]" class="delete" disabled="no-template" value="" /><button title="Delete Tier" class="scalable delete icon-btn delete-product-option" onclick="tierPriceControl.deleteItem(event);return false"><span>Delete</span></button></td>
                <!-- -/- -->
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td <?php if (!$_multiWebsite): ?>style="display:none"<?php endif; ?>></td>
                <td colspan="7" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>
            </tr>
        </tfoot>
        <tbody id="<?php echo $_htmlId ?>_container">
        </tbody>
    </table>
   
<script type="text/javascript">

//<![CDATA[
    var tierPriceControl = {
        template : new Template('<tr>' + $('<?php echo $_htmlId ?>_add_template').innerHTML.replace(/__index__/g, '#{index}').replace(/ disabled="?no-template"?/g, '').replace(/ disabled/g, '').replace(/="'([^']*)'"/g, '="$1"') + '</tr>'),
        itemsCount : 0,
        deleteButton: false,
        addItem  : function () {
			<?php if ($_readonly): ?>
            if (arguments.length < 4) {
                return;
            }
            <?php endif; ?>
			
            var data = {};
            data.website_id = 0;
            data.group = '<?php echo $this->getDefaultCustomerGroup() ?>';
            data.qty = '';
            data.price = '';
            data.index = this.itemsCount++;
            if(arguments.length == 6) {
                data.website_id = arguments[0];
                data.group      = arguments[1];
                data.qty        = arguments[2];
                data.price      = arguments[3];
                data.from_date  = arguments[4];
				data.to_date  = arguments[5];
            }
            Element.insert($('<?php echo $_htmlId ?>_container'), {'bottom':this.template.evaluate(data)});
            $('tier_price_row_'+data.index+'_cust_group').value = data.group;
            $('tier_price_row_'+data.index+'_website').value    = data.website_id;
			
			
            if (typeof(data.from_date) != "undefined")
			{
				var fdate=data.from_date.split("-");
				$('tier_price_row_'+data.index+'_from_date').value  = fdate[1]+"/"+fdate[2]+"/"+fdate[0];
			}
			else
				$('tier_price_row_'+data.index+'_from_date').value  = '';
			if (typeof(data.to_date) != "undefined")
			{
				var tdate=data.to_date.split("-");
				$('tier_price_row_'+data.index+'_to_date').value  = tdate[1]+"/"+tdate[2]+"/"+tdate[0];
			}
			else
				$('tier_price_row_'+data.index+'_to_date').value  = '';
			<?php if ($_readonly): ?>
            $('<?php echo $_htmlId ?>_container').select('input', 'select')
                .each(this.disableElement);
            $('<?php echo $_htmlId ?>_container').up('table').select('button')
                .each(this.disableElement);
            <?php endif; ?>
        },
        disableElement: function(elem) {
            elem.disabled = true
            elem.addClassName('disabled');
        },
        deleteItem : function(event) {
            var tr = Event.findElement(event, 'tr');
            if (tr) {
                Element.select(tr, '.delete').each(function(elem){elem.value='1'});
                Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
                Element.hide(tr);
                Element.addClassName(tr, 'no-display template');
            }
        }
    }
    <?php 

	
	foreach ($this->getValues() as $_item): ?>
 
    tierPriceControl.addItem('<?php echo $_item['website_id'] ?>', '<?php echo $_item['cust_group'] ?>', '<?php echo $_item['price_qty']*1 ?>','<?php echo sprintf('%.2f', $_item['price']) ?>','<?php echo $_item['from_date'] ?>','<?php echo $_item['to_date'] ?>');
    <?php endforeach; ?>
    <?php if ($_readonly): ?>
        $('<?php echo $_htmlId ?>_container').up('table').select('button')
            .each(tierPriceControl.disableElement);
    <?php endif; ?>
//]]>
</script>
</td>
</tr>